name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:

env:
  UPLOAD_IMAGE: true
  CUSTOMIZATION_SCRIPT: userpatches/customize-image.sh
  KERNEL_CONFIG: config
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download source code
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        git clone --depth=1 --branch=main https://github.com/armbian/build
     
    - name: Build Armbian image
      id: build
      run: |
        cd build
        ./compile.sh build BOARD=nanopineo BRANCH=legacy BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no RELEASE=bookworm
        echo "status=success" >> $GITHUB_ENV

    - name: Build summary
      id: build_summary
      run: |
        echo "| Property | Value |" >> summary.md
        echo "| :--- | :--- |" >> summary.md
        echo "| Name | NanoPi Neo |" >> summary.md
        echo "| Build | v${{ github.run_number }} |" >> summary.md

    - name: Encode summary
      id: encode_summary
      run: |
        summary=$(base64 -w 0 < summary.md)
        echo "summary_encoded=$summary" >> $GITHUB_ENV

    - name: Upload each Armbian file as release asset
      run: |
        for file in build/output/images/Armbian-unofficial*.img build/output/images/Armbian-unofficial*.img.sha build/output/images/Armbian-unofficial*.img.txt; do
          [ -e "$file" ] || continue
          gh release upload "v${{ github.run_number }}" "$file" --repo "${{ github.repository }}" --clobber
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        summary: ${{ env.summary }}

    - name: Create or update release
      run: |
        echo $summary_encoded | base64 --decode > decoded_summary.md
        gh release create "v${{ github.run_number }}" /dev/null --title "v${{ github.run_number }}" --notes-file decoded_summary.md --repo "${{ github.repository }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

