name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:

env:
  UPLOAD_IMAGE: true
  CUSTOMIZATION_SCRIPT: userpatches/customize-image.sh
  KERNEL_CONFIG: config
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download source code
      run: |
        pwd
        echo $GITHUB_WORKSPACE
        git clone --depth=1 --branch=main https://github.com/armbian/build
     
    - name: Build Armbian image
      id: build
      run: |
        cd build
        ./compile.sh build BOARD=nanopineo BRANCH=legacy BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no RELEASE=bookworm
        echo "status=success" >> $GITHUB_ENV

    - name: Archive IMG files
      id: archive_images
      run: |
        mkdir -p /tmp/archives
        for img_file in build/output/images/*.img; do
          archive_name=$(basename "${img_file}").tar.xz
          tar -Jcvf "/tmp/archives/$archive_name" *.img*
          echo "archive=$archive_name" >> $GITHUB_ENV
        done

    - name: Upload Armbian images
      id: upload_images
      uses: actions/upload-artifact@v4 # Updated to the latest version
      if: env.status == 'success'
      with:
        name: Armbian_images
        path: /tmp/archives/${{ env.archive }}
        
    - name: Build summary
      id: build_summary
      run: |
        echo "| Property | Value |" >> summary.md
        echo "| :--- | :--- |" >> summary.md
        echo "| Name | NanoPi Neo |" >> summary.md
        echo "| Build | v${{ github.run_number }} |" >> summary.md
        echo "build=v${{ github.run_number }}" >> $GITHUB_ENV
        echo "name=NanoPi-Neo" >> $GITHUB_ENV
        echo "title=NanoPi Neo Bookworm minimal" >> $GITHUB_ENV
        
    - name: Download Images from build
      uses: actions/download-artifact@v4
      with:
         name: Armbian_images

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
       repo_token: ${{ secrets.GITHUB_TOKEN }}
       file: ${{ env.ARCHIVE_PATHS }}
       asset_name: ${{ github.run_number }}-${{ env.archive }}
       tag: "v${{ github.run_number }}"
       overwrite: true
       body: ${{ steps.build_summary.outputs.summary }}
