name: Build Armbian

on:
  repository_dispatch:
  workflow_dispatch:

env:
  UPLOAD_IMAGE: true
  CUSTOMIZATIOM_SCRIPT: userpatches/customize-image.sh
  KERNEL_CONFIG: config
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download source code
      run: |
        pwd
        echo   $GITHUB_WORKSPACE
        git clone --depth=1 --branch=main https://github.com/armbian/build
     
    - name: build Armbian image
      id: build
      run: |
        cd build
        ./compile.sh build BOARD=nanopineo BRANCH=legacy BUILD_MINIMAL=no BUILD_DESKTOP=yes KERNEL_CONFIGURE=no RELEASE=bookworm
        echo "::set-output name=status::success"
        cd  output/images
        tar -Jcvf /tmp/nanopi_neo_image.tar.xz  *.img        

    - name: Upload Armbian image
      uses: actions/upload-artifact@master
      if: steps.build.outputs.status == 'success'
      with:
        name: Nanopi_neo_image
        path: /tmp/nanopi_neo_image.tar.xz
        
    - name: Upload artifact
      id: upload_artifact
      uses: actions/upload-artifact@v4
      with:
          name: nanopi-neo
          path: /tmp/nanopi_neo_image.tar.xz
      
    - name: Set artifact_url
      id: set_artifact_url
      run: echo "artifact_url=${{ steps.upload_artifact.outputs.artifact-url }}" >> $env:GITHUB_ENV
        
    - name: Build summary
      id: build_summary
      run: |
          Add-Content $env:GITHUB_STEP_SUMMARY @"
          | Property | Value |
          | :--- | :--- |
          | Name | NanoPi Neo |
          | Build | "v${{ github.run_number }}" |
          # Save the GITHUB_STEP_SUMMARY contents to a file
          (Get-Content $env:GITHUB_STEP_SUMMARY) | Set-Content summary.md
          echo "build="v${{ github.run_number }}" >> $env:GITHUB_ENV
          echo "name=NanoPi-Neo" >> $env:GITHUB_ENV
          echo "title=NanoPi Neo Bookworm minimal" >> $env:GITHUB_ENV
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.build }}"
        release_name: ${{ env.name }}
        body_path: summary.md
        draft: false
        prerelease: false

    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '7 days' # '<number> <unit>', e.g. 5 days, 2 years, 90 seconds, parsed by Moment.js
              # Optional inputs
              # skip-tags: true
              # skip-recent: 5
